stages:
    - Test
    - Snapshot
    - Release

TestDriver-Tests:
    stage: Test
    script:
        - |
            gradle setup test --no-daemon

# Immer
Snapshot:
    stage: Snapshot
    script:
        - |
            gradle snapshot -Penv=prod --no-daemon

# Nur getaggte Versionen:
Release:
    stage: Release
    only:
      - tags
    script:
        - |
            gradle release -Penv=prod --no-daemon
